version: '3.8'
services:
  web:
    build: ..
    command: gunicorn qro_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=0
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quickbite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:1.25-alpine
    ports:
      - '80:80'
    volumes:
      - static_volume:/app/staticfiles:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  pgdata:
  static_volume:
  media_volume:
